#ifndef __TANGOX_IRQ_H
#define __TANGOX_IRQ_H

#define IRQ_BASE		8
#define FIQ_BASE		72
#define IIQ_BASE		136

#define UART0_IRQ		(IRQ_BASE + 1)
#define UART1_IRQ		(IRQ_BASE + 2)
#define SFLA_IRQ		(IRQ_BASE + 4)
#define TIMER0_IRQ		(IRQ_BASE + 5)
#define TIMER1_IRQ		(IRQ_BASE + 6)
#define DVD_IRQ			(IRQ_BASE + 7)
#define RTC_IRQ			(IRQ_BASE + 8)
#define DMA_W0_IRQ		(IRQ_BASE + 9)
#define DMA_W1_IRQ		(IRQ_BASE + 10)
#define DMA_R0_IRQ		(IRQ_BASE + 11)
#define DMA_R1_IRQ		(IRQ_BASE + 12)
#define PCI_A_IRQ		(IRQ_BASE + 13)
#define PCI_B_IRQ		(IRQ_BASE + 14)
#define PCI_C_IRQ		(IRQ_BASE + 15)
#define PCI_D_IRQ		(IRQ_BASE + 16)
#define DMAIDE_IRQ		(IRQ_BASE + 17)
#define IDE_IRQ			(IRQ_BASE + 18)
#define FRONTPANEL_IRQ		(IRQ_BASE + 19)
#define PCI_FAULT_IRQ		(IRQ_BASE + 20)
#define INFRARED_IRQ		(IRQ_BASE + 21)
#define I2C_IRQ			(IRQ_BASE + 22)
#define GFX_ACCEL_IRQ		(IRQ_BASE + 23)
#define VSYNC0_IRQ		(IRQ_BASE + 24)
#define VSYNC1_IRQ		(IRQ_BASE + 25)
#define VSYNC2_IRQ		(IRQ_BASE + 26)
#define VSYNC3_IRQ		(IRQ_BASE + 27)
#define VSYNC4_IRQ		(IRQ_BASE + 28)
#define VSYNC4BKEND_IRQ		(IRQ_BASE + 29)
#define VSYNC5_IRQ		(IRQ_BASE + 30)
#define VSYNC5BKEND_IRQ		(IRQ_BASE + 31)
#define SCARD0_IRQ		(IRQ_BASE + 32)
#define HDMI_IRQ		(IRQ_BASE + 33)
#define HDMI_I2C_IRQ		(IRQ_BASE + 34)
#define VBUS_W0_IRQ		(IRQ_BASE + 35)
#define VBUS_W3_IRQ		(IRQ_BASE + 36)
#define ETH0_PHY_IRQ		(IRQ_BASE + 37)
#define ETH0_MAC_IRQ		(IRQ_BASE + 38)
#define USB0_OHCI_IRQ		(IRQ_BASE + 39)
#define USB0_EHCI_IRQ		(IRQ_BASE + 40)
#define SATA0_IRQ		(IRQ_BASE + 41)
#define SATA0_DMA_IRQ		(IRQ_BASE + 42)
#define XPU_W0_IRQ		(IRQ_BASE + 43)
#define XPU_R0_IRQ		(IRQ_BASE + 44)
#define XPU_W_SP_IRQ		(IRQ_BASE + 45)
#define XPU_R_SP_IRQ		(IRQ_BASE + 46)
#define GPIO24_IRQ		(IRQ_BASE + 47)
#define GPIO25_IRQ		(IRQ_BASE + 48)
#define GPIO26_IRQ		(IRQ_BASE + 49)
#define GPIO27_IRQ		(IRQ_BASE + 50)
#define VBUS_W4_IRQ		(IRQ_BASE + 51)
#define SCARD1_IRQ		(IRQ_BASE + 52)
#define HDMI_CEC_IRQ		(IRQ_BASE + 53)
#define SATA1_IRQ		(IRQ_BASE + 54)
#define SATA1_DMA_IRQ		(IRQ_BASE + 55)
#define ETH1_PHY_IRQ		(IRQ_BASE + 56)
#define ETH1_MAC_IRQ		(IRQ_BASE + 57)
#define DMA_W2_IRQ		(IRQ_BASE + 58)
#define DMA_R2_IRQ		(IRQ_BASE + 59)
#define SDIO0_IRQ		(IRQ_BASE + 60)
#define SDIO1_IRQ		(IRQ_BASE + 61)
#define SPI_IRQ			(IRQ_BASE + 62)
#define UART2_IRQ		(IRQ_BASE + 63)

#endif /* __TANGOX_IRQ_H */
